server:
  port: 8088

# Spring
spring:
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123qwe

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none

